name: debug

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
  workflow_dispatch:


jobs:

  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: install default deps
        run: sudo apt -o Acquire::Retries=3 update && sudo apt -o Acquire::Retries=3 install make ftp git bzr curl wget -y 
      - name: upgrade apt-get
        run: |
          sudo apt-get upgrade -y
      - name: upgrade apt
        run: |
          sudo apt upgrade -y
