name: Go

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - '**'

jobs:

  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: install deps
        run: sudo apt-get install make ftp git bzr curl hwloc libhwloc-dev mesa-opencl-icd ocl-icd-opencl-dev wget -y && sudo apt upgrade -y

      - name: dep
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GO111MODULE: "on"
        run: |
          make deps

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Test
        run: go test -v ./...

      - name: compatible all
        run: |
          make compatible-all

      - name: gen all
        run: |
          make gen-all

      - name: detect changes
        run: |
          git status --porcelain
          test -z "$(git status --porcelain)"

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GO111MODULE: "on"
        run: |
          make

      - name: Run coverage
        run:  go test -coverpkg=./... -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          token:
          files: ./coverage.txt
          flags: unittests
          name: venus-market
          fail_ci_if_error: true
          verbose: true